name: ddocdoc_clone
description: "Ddocdoc Clone Project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_local_notifications: ^17.0.0
  flutter_naver_map: ^1.2.2
  geolocator: ^11.0.0
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  permission_handler: ^11.3.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
